<h3 style="color:blue"><i>Numpy</i></h3>

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [8]:
import numpy as np
arr=np.array([1,2,3,4,"Hi"])
arr

array(['1', '2', '3', '4', 'Hi'], dtype='<U21')

In [11]:
l=[10,20,30]*2
l

[10, 20, 30, 10, 20, 30]

In [23]:
arr_1D=np.array([1,2,3])
arr_2D=np.array([[1,2,3],
                [4,5,6]])
arr_3D=np.array([[[10,20,30]]])
print(arr_1D.ndim) #Used to check the dimension of the array
print(arr_2D.ndim)
print(arr_3D.ndim)

1
2
3


In [25]:
arr_2D=np.array([[1,2,3],
                [4,5,6]])
arr_2D.shape  #used to check the no.of rows anf columns
arr_2D.shape  

(2, 3)

In [ ]:
 np.array()  - used to create numpy array
 np.arange() - to generate a sequence of numbers in numpy
 np.append(value,array_name)
 np.append() - used to add elements to an existing array

In [27]:
arr=np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
arr=np.arange(10,20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [29]:
arr=np.arange(10,20)
arr=np.append(arr,100)
arr


array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19, 100])

In [32]:
arr=np.arange(10,20)
arr=np.append(100,arr)
arr


array([100,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

Boolean Masking

Boolean masking is a NumPy technique that uses a Boolean array (an array of True and False values) to select, filter, or modify elements in another array based on a specified condition.

In [34]:
arr=np.array([80,10,30,40,65])
bool_mask=arr>50
arr[bool_mask]

array([80, 65])

In [36]:
arr=np.array([80,10,30,40,65])
bool_mask=arr>20
arr[bool_mask]

array([80, 30, 40, 65])

In [41]:
arr=np.array([80,10,30,40,65])
print(arr>50)

[ True False False False  True]


In [42]:
arr=np.array([80,10,30,40,65])
print(arr>40)

[ True False False False  True]


In [ ]:
print(arr[-1])    #np array support +ve index
print(arr[0])     #np array support -ve index
print(arr[::-1])  #reverse the array
print(arr[0:3])   #support slicing

In [43]:
arr=np.array([80,10,3,20,40,65])
result=np.where(arr>50,arr*2,arr)
#Syntx: np.where("Condition",true,false)
result

array([160,  10,   3,  20,  40, 130])

In [ ]:
order_amount=1000 1500 800 3000 4000 900
1.filter order_amount>2000
2.order_amount>2000 must be multiply by 2 
3.add new order_amount at the end 5000
4.print the last order amount

In [44]:
import numpy as np

# Create the array
order_amount = np.array([1000, 1500, 800, 3000, 4000, 900])

# 1. Filter order_amount > 2000
print("1. Order amounts > 2000:")
print(order_amount[order_amount > 2000])

# 2. Multiply order_amount > 2000 by 2
order_amount[order_amount > 2000] *= 2
print("\n2. After multiplying by 2:")
print(order_amount)

# 3. Add new order_amount at the end (5000)
order_amount = np.append(order_amount, 5000)
print("\n3. After adding 5000:")
print(order_amount)

# 4. Print the last order amount
print("\n4. Last order amount:")
print(order_amount[-1])

1. Order amounts > 2000:
[3000 4000]

2. After multiplying by 2:
[1000 1500  800 6000 8000  900]

3. After adding 5000:
[1000 1500  800 6000 8000  900 5000]

4. Last order amount:
5000


In [47]:
order_amount=np.array(list(map(int,input("Enter the amount:").split())))
print(order_amount)
print("order>2000:",order_amount[order_amount>2000])
print("order>2000 multi of 2:")
print(np.where(order_amount>2000,order_amount*2,order_amount))
order_amount=np.append(order_amount,5000)
print("new order added:",order_amount)
print("last order amount:",order_amount[-1])

Enter the amount:1000 1500 800 3000 4000 900
[1000 1500  800 3000 4000  900]
order>2000: [3000 4000]
order>2000 multi of 2:
[1000 1500  800 6000 8000  900]
new order added: [1000 1500  800 3000 4000  900 5000]
last order amount: 5000


In [49]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
final_arr=np.concatenate([arr1,arr2])
final_arr

array([1, 2, 3, 4, 5, 6])

In [50]:
arr=np.arange(1,10)
arr_2d=arr.reshape(3,3) #convert arr into other dimensions
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr=np.array([10,20,30,10,20])
print(np.unique(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.nbytes) #40
print(arr.itemsize) #40/5

[10 20 30]
1
(5,)
5
40
8


In [54]:
arr=np.zeros((2,3),dtype=int) #try=>np.ones
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [55]:
arr=np.ones((2,3),dtype=int) #try=>np.ones
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [59]:
arr=np.ones((2,3),dtype=int) 
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [62]:
import numpy as np
n=np.random.choice(np.arange(1,100))
print(n)

55


In [67]:
import numpy as np
np.random.seed(20)  # seed used for reproducability
n=np.random.choice(np.arange(1,100))
print(n)                                

20


In [68]:
import numpy as np
np.random.seed(0)
n=np.random.choice(np.arange(1,100))
arr=np.random.randint(10)
print(n) 

45


In [76]:
import numpy as np
np.random.seed(0)  
n=np.random.choice(np.arange(1,100))
arr_1d=np.random.randint(10,size=(3))
arr_2d=np.random.randint(10,size=(2,4))
arr_3d=np.random.randint(10,size=(2,4,1))
print(arr_3d.ndim)
print(arr_2d.ndim)
print(arr_1d.ndim)
print(n) 

3
2
1
45


In [73]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [74]:
np.linspace(1,2,4)

array([1.        , 1.33333333, 1.66666667, 2.        ])

Broadcasting

In [75]:
arr1=np.array([[1,3],
              [4,5]])
arr2=np.array([2])
arr1*arr2

array([[ 2,  6],
       [ 8, 10]])

In [77]:
arr1.T  #transpose


array([[1, 4],
       [3, 5]])

In [78]:
np.sum(arr1)

13

In [84]:
#Aggregate functions!!!!!!! min(),max(),sum(),count()
print("Sum of values of arr1",np.sum(arr1))
print("Max value of arr1:",np.max(arr1))
print("min value of arr2:",np.min(arr2))

Sum of values of arr1 13
Max value of arr1: 5
min value of arr2: 2


In [81]:
#Aggregate functions!!!!!!! min(),max(),sum(),count()
print("Sum of values of arr1",np.sum(arr1))
print("Max value of arr1:",np.max(arr1))
print("min value of arr1:",np.min(arr1))

Sum of values of arr1 13
Max value of arr1: 5
min value of arr1: 1


In [86]:
s1="cat"   #check anagram
s2="act"
if sorted(s1)==sorted(s2):
    print("It is an Anagram")
else:
    print("Not an Anagram")


It is an Anagram


In [89]:
s1="cap"   #check anagram
s2="apc"
if sorted(s1)==sorted(s2):
    print("It is an Anagram")
else:
    print("Not an Anagram")


It is an Anagram
